<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:property name="WheelBase" value="0.32" />
  <xacro:property name="WheelLength" value="0.2055" />

  <xacro:property name="ChassisSize_L" value="0.49"/>
  <xacro:property name="ChassisSize_B" value="0.18"/>
  <xacro:property name="ChassisSize_H" value="0.05"/>
  <xacro:property name="ChassisMass" value="3.5"/>

  <xacro:property name="WheelSize_r" value="0.05" />
  <xacro:property name="WheelSize_h" value="0.035" />
  <xacro:property name="WheelMass" value="0.2" />

  <xacro:property name="SteeringSize_r" value="0.01" />
  <xacro:property name="SteeringMass" value="0.07" />

  <xacro:property name="SteeringAnger_deg" value="530.0" />
  <xacro:property name="SteerAnger_deg" value="30.0" />
  <xacro:property name="Speed_m_s" value="10.0" />

  <!-- Wheel macro -->
  <xacro:macro name="wheel" params="fb lr parent translateX translateY left OffsetJointX OffsetJointY OffsetY">
    <link name="${lr}_wheel_${fb}">
      <inertial>
        <mass value="${WheelMass}" />
        <origin xyz="0 ${OffsetY} 0" rpy="${90*pi/180} 0 0"/>
        <xacro:cylinder_inertia  m="${WheelMass}" r="${WheelSize_r}" h="${WheelSize_h}" />
      </inertial>

      <collision>
        <origin xyz="0 ${OffsetY} 0" rpy="${90*pi/180} 0 0 " />
        <geometry>
          <cylinder length="${WheelSize_h}" radius="${WheelSize_r}" />
        </geometry>
      </collision>

      <visual>
        <origin xyz="0 ${OffsetY} 0" rpy="${90*pi/180} 0 ${left*pi}" />
        <geometry>
          <cylinder length="${WheelSize_h}" radius="${WheelSize_r}" />
        </geometry>
        <material name="black"/>
      </visual>
    </link>

    <joint name="${lr}_wheel_${fb}_hinge" type="continuous">
      <parent link="${parent}"/>
      <child link="${lr}_wheel_${fb}"/>
      <origin xyz="${translateX * OffsetJointX} ${translateY * OffsetJointY} 0.0" rpy="0 0 0" />
      <axis xyz="0 1 0" rpy="0 0 0" />
      <limit effort="20" velocity="500"/>
      <joint_properties damping="1e-9" friction="1e-9"/>
    </joint>

    <transmission name="${lr}_wheel_${fb}_transmission" type="SimpleTransmission">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="${lr}_wheel_${fb}_hinge">
        <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      </joint>
      <actuator name="${lr}_wheel_${fb}_motor">
        <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
        <mechanicalReduction>1</mechanicalReduction>
      </actuator>
    </transmission>

    <gazebo reference="${lr}_wheel_${fb}">
      <material>Gazebo/Black</material>
      <mu1>0.9</mu1>
      <mu2>0.9</mu2>
    </gazebo>
  </xacro:macro>

  <!-- Steering macro -->
  <xacro:macro name="steering_hinge" params="lr parent translateY OffsetY">
    <link name="${lr}_steering">
      <inertial>
        <mass value="${SteeringMass}" />
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <xacro:sphere_inertia  m="${SteeringMass}" r="${SteeringSize_r}" />
      </inertial>

      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <sphere radius="${SteeringSize_r}"/>
        </geometry>
      </visual>
    </link>

    <gazebo reference="${lr}_steering">
      <material>Gazebo/Grey</material>
    </gazebo>

    <joint name="${lr}_steering_hinge" type="revolute">
      <origin xyz="${WheelBase/2} ${translateY * WheelLength/2} 0" rpy="0 0 0" />
      <parent link="${parent}" />
      <child link="${lr}_steering" />
      <axis xyz="0 0 1" />
      <limit lower="${-1*SteerAnger_deg*pi/180}" upper="${SteerAnger_deg*pi/180}" effort="10" velocity="100" />
    </joint>

    <transmission name="${lr}_steering_hinge_transmission" type="SimpleTransmission">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="${lr}_steering_hinge">
        <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      </joint>
      <actuator name="${lr}_steering_hinge_motor">
        <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
        <mechanicalReduction>1</mechanicalReduction>
      </actuator>
    </transmission>
  </xacro:macro>



  <!--  Base Link  -->
  <link name="base_link" />

  <!--  Chassis  -->
  <joint name="base_link_joint" type="fixed">
    <origin xyz="${WheelBase/2} 0 ${WheelSize_r}" rpy="0 0 0" />
    <parent link="base_link" />
    <child link="chassis" />
  </joint>

  <link name='chassis'>
    <inertial>
      <mass value="${ChassisMass}"/>
      <origin xyz="0 0 0" rpy=" 0 0 0"/>
      <xacro:box_inertia m="${ChassisMass}" l="${ChassisSize_L}" b="${ChassisSize_B}" h="${ChassisSize_H}" />
    </inertial>

    <collision name='collision'>
      <origin xyz="0 0 0" rpy=" 0 0 0"/>
      <geometry>
        <box size="${ChassisSize_L} ${ChassisSize_B} ${ChassisSize_H}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 0" rpy=" 0 0 0"/>
      <geometry>
        <box size="${ChassisSize_L} ${ChassisSize_B} ${ChassisSize_H}"/>
      </geometry>
      <material name="yellow"/>
    </visual>
  </link>

  <gazebo reference="chassis">
    <material>Gazebo/Yellow</material>
  </gazebo>

  <!--  Steering wheel  -->
  <joint name="steering_wheel_joint" type="continuous">
    <origin xyz="${-1*WheelBase/2} 0 ${ChassisSize_H/2 + 0.01}" rpy="0 0 0" />
    <parent link="chassis" />
    <child link="steering_wheel" />
    <axis xyz="1 0 0" />
    <limit lower="${-1*SteeringAnger_deg*pi/180}" upper="${SteeringAnger_deg*pi/180}" effort="10000000" velocity="1000000"/>
  </joint>

  <link name='steering_wheel'>
    <inertial>
      <mass value="0.1"/>
      <xacro:box_inertia m="0.1" l="0.01" b="0.01" h="0.01" />
    </inertial>
    <collision name='collision'>
      <geometry>
        <box size="0.01 0.01 0.01"/>
      </geometry>
    </collision>
    <visual>
      <origin xyz="0 0 0" rpy=" 0 0 0"/>
      <geometry>
        <box size="0.01 0.01 0.01"/>
      </geometry>
      <material name="yellow"/>
    </visual>
  </link>

  <gazebo reference="steering_wheel">
    <material>Gazebo/Yellow</material>
  </gazebo>

  <!--  Wheels  -->
  <xacro:wheel fb="front" lr="left" parent="left_steering"
    translateX="1" translateY="1" left="1"
    OffsetJointX= "0" OffsetJointY= "0.001" OffsetY="0.02" />

  <xacro:wheel fb="front" lr="right" parent="right_steering"
    translateX="1" translateY="-1" left="0"
    OffsetJointX= "0" OffsetJointY= "0.001" OffsetY="-0.02" />

  <xacro:wheel fb="back" lr="left" parent="chassis"
    translateX="-1" translateY="1" left="1"
    OffsetJointX= "${WheelBase/2}" OffsetJointY= "${WheelLength/2}" OffsetY="0.021" />

  <xacro:wheel fb="back" lr="right" parent="chassis"
    translateX="-1" translateY="-1" left="0"
    OffsetJointX= "${WheelBase/2}" OffsetJointY= "${WheelLength/2}" OffsetY="-0.021" />


  <!--  Steering  -->
  <xacro:steering_hinge lr="left" parent="chassis" translateY="1" OffsetY="0.02" />
  <xacro:steering_hinge lr="right" parent="chassis" translateY="-1" OffsetY="-0.02" />


  <!-- Plugins -->

  <!-- Ackermann drive -->
  <gazebo>
    <plugin name='ackermann_drive' filename='libgazebo_ros_ackermann_drive.so'>
      <update_rate>100.0</update_rate>

      <!-- wheels -->
      <front_left_joint>left_wheel_front_hinge</front_left_joint>
      <front_right_joint>right_wheel_front_hinge</front_right_joint>
      <rear_left_joint>left_wheel_back_hinge</rear_left_joint>
      <rear_right_joint>right_wheel_back_hinge</rear_right_joint>
      <left_steering_joint>left_steering_hinge</left_steering_joint>
      <right_steering_joint>right_steering_hinge</right_steering_joint>
      <steering_wheel_joint>steering_wheel_joint</steering_wheel_joint>

      <!-- Max absolute steer angle for tyre in radians-->
      <!-- Any cmd_vel angular z greater than this would be capped -->
      <max_steer>${SteerAnger_deg*pi/180}</max_steer>

      <!-- Max absolute steering angle of steering wheel -->
      <max_steering_angle>${SteeringAnger_deg*pi/180}</max_steering_angle>

      <!-- Max absolute linear speed in m/s -->
      <max_speed>${Speed_m_s}</max_speed>

      <left_steering_pid_gain>5 0 0.3</left_steering_pid_gain>
      <left_steering_i_range>0 0</left_steering_i_range>
      <right_steering_pid_gain>5 0 0.3</right_steering_pid_gain>
      <right_steering_i_range>0 0</right_steering_i_range>
      <linear_velocity_pid_gain>0.5 0 0</linear_velocity_pid_gain>
      <linear_velocity_i_range>0 0</linear_velocity_i_range>

      <!-- output -->
      <publish_odom>true</publish_odom>
      <publish_odom_tf>true</publish_odom_tf>
      <publish_wheel_tf>false</publish_wheel_tf>
      <publish_distance>true</publish_distance>

      <odometry_frame>odom</odometry_frame>
      <robot_base_frame>base_link</robot_base_frame>

      <ros>
        <argument>--ros-args --remap cmd_vel:=cmd_vel</argument>
        <argument>--ros-args --remap odom:=odom</argument>
        <argument>--ros-args --remap distance:=distance</argument>
        <remapping>/tf:=tf</remapping>
      </ros>

    </plugin>
  </gazebo>

  <gazebo>
    <plugin name="robot_joint_state" filename="libgazebo_ros_joint_state_publisher.so">
      <ros>
        <remapping>~/out:=joint_states</remapping>
      </ros>
      <update_rate>100</update_rate>
      <joint_name>left_wheel_front_hinge</joint_name>
      <joint_name>right_wheel_front_hinge</joint_name>
      <joint_name>left_wheel_back_hinge</joint_name>
      <joint_name>right_wheel_back_hinge</joint_name>
      <joint_name>left_steering_hinge</joint_name>
      <joint_name>right_steering_hinge</joint_name>
      <joint_name>steering_wheel_joint</joint_name>
    </plugin>
  </gazebo>

</robot>