<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">

  <!-- Properties -->

  <xacro:property name="hokuyoSize" value="0.1"/>
  <xacro:property name="hokuyoMass" value="0.1"/>

  <!-- Hokuyo Laser -->
  <link name="laser_link">
    <inertial>
      <mass value="${hokuyoMass}" />
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <xacro:box_inertia m="${hokuyoMass}" l="${hokuyoSize}" b="${hokuyoSize}" h="${hokuyoSize}" />
    </inertial>

    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${hokuyoSize} ${hokuyoSize} ${hokuyoSize}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${hokuyoSize} ${hokuyoSize} ${hokuyoSize}"/>
      </geometry>
      <material name="blue"/>
    </visual>
  </link>

  <joint name="laser_joint" type="fixed">
    <axis xyz="0 1 0" />
    <origin xyz="0.0 0 ${imu2chassisZ/2+hokuyoSize/2+0.01}" rpy="0 0 0"/>
    <parent link="imu_link"/>
    <child link="laser_link"/>
  </joint>

  <!-- Laser Sensor -->
  <gazebo reference="laser_link">
    <material>Gazebo/Blue</material>
    <sensor name="laser_sensor" type="ray">
    <always_on>true</always_on>
    <visualize>true</visualize>
    <update_rate>5</update_rate>
    <pose>0 0 0.075 0 0 0</pose>
    <ray>
        <scan>
          <horizontal>
            <samples>360</samples>
            <resolution>1.000000</resolution>
            <min_angle>0.000000</min_angle>
            <max_angle>6.280000</max_angle>
          </horizontal>
        </scan>
        <range>
          <min>0.120000</min>
          <max>3.5</max>
          <resolution>0.015000</resolution>
        </range>
        <noise>
          <type>gaussian</type>
          <mean>0.0</mean>
          <stddev>0.01</stddev>
        </noise>
    </ray>

    <plugin name="laserscan" filename="libgazebo_ros_ray_sensor.so">
      <ros>
        <!-- <namespace>/tb3</namespace> -->
        <remapping>~/out:=scan</remapping>
      </ros>
      <output_type>sensor_msgs/LaserScan</output_type>
      <frame_name>laser_link</frame_name>
    </plugin>
    </sensor>
  </gazebo>

</robot>